"""group_student relation

Revision ID: ee69d846d3b2
Revises: 3d59b58ca4e1
Create Date: 2025-09-15 10:31:43.207566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee69d846d3b2'
down_revision: Union[str, Sequence[str], None] = '3d59b58ca4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupstudent',
    sa.Column('group_fk', sa.Integer(), nullable=False),
    sa.Column('student_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_fk'], ['group.id'], ),
    sa.PrimaryKeyConstraint('group_fk', 'student_fk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupstudent')
    # ### end Alembic commands ###
