default_language_version:
  python: python3.11

files: ^code/

fail_fast: true

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix, --indent=2 ]
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace
      - id: requirements-txt-fixer
#      - id: no-commit-to-branch
#        args: [ --branch, develop, --branch, dev, --branch, main, --branch, master ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma
        stages:
          - pre-commit
        types: [ python ]

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-builtins
          - flake8-print
          - flake8-debugger
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-django

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (import sorting)
        args: [--sp=.isort.cfg]
        stages:
          - pre-commit
        types: [python]
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
        additional_dependencies:
          - flake8-quotes
          - flake8-bugbear
#          - flake8-builtins
          - flake8-print
          - flake8-debugger
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate
        types: [python]
        language_version: python3

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-unused-variables,
          ]
        types: [ python ]
