"""add fields into user

Revision ID: c0ba39ea2bb5
Revises: 1437758de114
Create Date: 2025-09-02 10:28:46.958520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ba39ea2bb5'
down_revision: Union[str, Sequence[str], None] = '1437758de114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_column('user', 'role')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'username')
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###
